/** Maps team names (case-insensitive) to flagcdn.com country codes */
const TEAM_CODES: Record<string, string> = {
  // CONMEBOL
  "argentina":                  "ar",
  "brazil":                     "br",
  "brasil":                     "br",
  "uruguay":                    "uy",
  "colombia":                   "co",
  "ecuador":                    "ec",
  "venezuela":                  "ve",
  "paraguay":                   "py",
  "peru":                       "pe",
  "perú":                       "pe",
  "chile":                      "cl",
  "bolivia":                    "bo",

  // UEFA
  "spain":                      "es",
  "españa":                     "es",
  "france":                     "fr",
  "francia":                    "fr",
  "germany":                    "de",
  "alemania":                   "de",
  "england":                    "gb-eng",
  "inglaterra":                 "gb-eng",
  "portugal":                   "pt",
  "netherlands":                "nl",
  "países bajos":               "nl",
  "paises bajos":               "nl",
  "holland":                    "nl",
  "holanda":                    "nl",
  "belgium":                    "be",
  "bélgica":                    "be",
  "belgica":                    "be",
  "italy":                      "it",
  "italia":                     "it",
  "switzerland":                "ch",
  "suiza":                      "ch",
  "croatia":                    "hr",
  "croacia":                    "hr",
  "austria":                    "at",
  "denmark":                    "dk",
  "dinamarca":                  "dk",
  "turkey":                     "tr",
  "türkiye":                    "tr",
  "turquia":                    "tr",
  "turquía":                    "tr",
  "scotland":                   "gb-sct",
  "escocia":                    "gb-sct",
  "czech republic":             "cz",
  "czechia":                    "cz",
  "república checa":            "cz",
  "republica checa":            "cz",
  "greece":                     "gr",
  "grecia":                     "gr",
  "serbia":                     "rs",
  "slovakia":                   "sk",
  "eslovaquia":                 "sk",
  "poland":                     "pl",
  "polonia":                    "pl",
  "hungary":                    "hu",
  "hungría":                    "hu",
  "hungria":                    "hu",
  "wales":                      "gb-wls",
  "gales":                      "gb-wls",
  "ukraine":                    "ua",
  "ucrania":                    "ua",
  "romania":                    "ro",
  "rumania":                    "ro",
  "albania":                    "al",
  "slovenia":                   "si",
  "eslovenia":                  "si",
  "iceland":                    "is",
  "islandia":                   "is",
  "norway":                     "no",
  "noruega":                    "no",
  "sweden":                     "se",
  "suecia":                     "se",
  "finland":                    "fi",
  "finlandia":                  "fi",
  "israel":                     "il",
  "georgia":                    "ge",
  "kosovo":                     "xk",
  "montenegro":                 "me",
  "north macedonia":            "mk",
  "macedonia del norte":        "mk",
  "luxembourg":                 "lu",
  "luxemburgo":                 "lu",
  "northern ireland":           "gb-nir",
  "irlanda del norte":          "gb-nir",
  "ireland":                    "ie",
  "irlanda":                    "ie",
  "russia":                     "ru",
  "rusia":                      "ru",
  "bosnia":                     "ba",
  "bosnia and herzegovina":     "ba",
  "bulgaria":                   "bg",
  "moldova":                    "md",
  "latvia":                     "lv",
  "lithuania":                  "lt",
  "estonia":                    "ee",
  "belarus":                    "by",
  "bielorusia":                 "by",
  "liechtenstein":              "li",
  "san marino":                 "sm",
  "andorra":                    "ad",
  "malta":                      "mt",
  "gibraltar":                  "gi",
  "faroe islands":              "fo",
  "islas feroe":                "fo",
  "cyprus":                     "cy",
  "chipre":                     "cy",
  "armenia":                    "am",
  "azerbaijan":                 "az",
  "kazakstan":                  "kz",

  // CONCACAF
  "curaçao":                    "cw",
  "curacao":                    "cw",
  "united states":              "us",
  "usa":                        "us",
  "estados unidos":             "us",
  "mexico":                     "mx",
  "méxico":                     "mx",
  "canada":                     "ca",
  "canadá":                     "ca",
  "panama":                     "pa",
  "panamá":                     "pa",
  "honduras":                   "hn",
  "jamaica":                    "jm",
  "costa rica":                 "cr",
  "el salvador":                "sv",
  "guatemala":                  "gt",
  "trinidad and tobago":        "tt",
  "trinidad y tobago":          "tt",
  "haiti":                      "ht",
  "haití":                      "ht",
  "cuba":                       "cu",
  "nicaragua":                  "ni",

  // CAF
  "morocco":                    "ma",
  "marruecos":                  "ma",
  "senegal":                    "sn",
  "egypt":                      "eg",
  "egipto":                     "eg",
  "nigeria":                    "ng",
  "south africa":               "za",
  "sudáfrica":                  "za",
  "sudafrica":                  "za",
  "ivory coast":                "ci",
  "côte d'ivoire":              "ci",
  "cote d'ivoire":              "ci",
  "costa de marfil":            "ci",
  "cameroon":                   "cm",
  "camerún":                    "cm",
  "camerun":                    "cm",
  "ghana":                      "gh",
  "algeria":                    "dz",
  "argelia":                    "dz",
  "túnez":                      "tn",
  "tunez":                      "tn",
  "tunisia":                    "tn",
  "mali":                       "ml",
  "malí":                       "ml",
  "dr congo":                   "cd",
  "congo dr":                   "cd",
  "democratic republic of congo": "cd",
  "congo":                      "cg",
  "mozambique":                 "mz",
  "tanzania":                   "tz",
  "ethiopia":                   "et",
  "etiopía":                    "et",
  "zambia":                     "zm",
  "zimbabwe":                   "zw",
  "uganda":                     "ug",
  "kenya":                      "ke",
  "rwanda":                     "rw",
  "guinea":                     "gn",
  "equatorial guinea":          "gq",
  "guinea ecuatorial":          "gq",
  "cape verde":                 "cv",
  "burkina faso":               "bf",
  "libya":                      "ly",
  "libia":                      "ly",
  "sudan":                      "sd",
  "sudán":                      "sd",
  "benin":                      "bj",
  "bénin":                      "bj",
  "mauritania":                 "mr",
  "gabon":                      "ga",
  "gabón":                      "ga",
  "angola":                     "ao",
  "botswana":                   "bw",
  "namibia":                    "na",
  "comoros":                    "km",
  "comoras":                    "km",

  // AFC
  "japan":                      "jp",
  "japón":                      "jp",
  "japon":                      "jp",
  "south korea":                "kr",
  "korea republic":             "kr",
  "república de corea":         "kr",
  "corea del sur":              "kr",
  "iran":                       "ir",
  "irán":                       "ir",
  "australia":                  "au",
  "saudi arabia":               "sa",
  "arabia saudita":             "sa",
  "qatar":                      "qa",
  "catar":                      "qa",
  "china":                      "cn",
  "china pr":                   "cn",
  "uzbekistan":                 "uz",
  "uzbekistán":                 "uz",
  "iraq":                       "iq",
  "irak":                       "iq",
  "jordan":                     "jo",
  "jordania":                   "jo",
  "kyrgyzstan":                 "kg",
  "kirguistán":                 "kg",
  "oman":                       "om",
  "omán":                       "om",
  "india":                      "in",
  "bahrain":                    "bh",
  "baréin":                     "bh",
  "united arab emirates":       "ae",
  "emiratos arabes unidos":     "ae",
  "tajikistan":                 "tj",
  "indonesia":                  "id",
  "vietnam":                    "vn",
  "thailand":                   "th",
  "tailandia":                  "th",
  "north korea":                "kp",
  "corea del norte":            "kp",
  "dpr korea":                  "kp",
  "myanmar":                    "mm",
  "singapore":                  "sg",
  "philippines":                "ph",
  "filipinas":                  "ph",
  "malaysia":                   "my",
  "china taipei":               "tw",
  "chinese taipei":             "tw",
  "hong kong":                  "hk",
  "nepal":                      "np",

  // OFC
  "new zealand":                "nz",
  "nueva zelanda":              "nz",
  "tahiti":                     "pf",
  "tahití":                     "pf",
  "solomon islands":            "sb",
  "islas salomón":              "sb",
  "fiji":                       "fj",
  "papua new guinea":           "pg",
  "vanuatu":                    "vu",
  "samoa":                      "ws",
  "tonga":                      "to",
};

export function teamToCountryCode(name: string): string {
  return TEAM_CODES[name.toLowerCase().trim()] ?? "";
}
